apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host_mnt/c/Users/Carlos.Herrera/Desktop/ELKK8s/elasticsearch/data
