apiVersion: v1
kind: PersistentVolume
metadata:
  name: logstash-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /host_mnt/c/Users/Carlos.Herrera/Desktop/ELKK8s/logs
