apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      file {
        path => "/usr/share/logstash/logs/*.log"
        start_position => "beginning"
      }
    }
    filter {
      # Define your filter configuration here
    }
    output {
      elasticsearch {
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
      }
    }
